### ISSUE TITLE
{Question} About the underlying concept

### ISSUE THREAD

**Issue by Suleman-Elahi** [Hameds/RostamBot#32]
Hi,

I am thinking of making a similar tool in Python/Django for Twitter India. I have two questions for you; how did you achieve mass blocking and how are you identifying if a given account is fake. DotNet is far away from expertise and hence I can't understand with the code. Do you have a documentation of something like that for RostamBot?

Thank you

**Comment by Hameds** [comment]
@Suleman-Elahi Hi,

Unfortunately, I don't have any documentation. Here is the summary of how it works:
- Rostambot can receive mentions or direct messages on Twitter.
- Rostambot will save received reports to the database.
- Human moderators will decide about reported accounts.
- If an account is flagged by a moderator, it will update the block list of all users who authorized Rostambot on Twitter.
- Rostambot provides API.

Important note: always work with Twitter ID instead of the username. These accounts can change their name, username, profile image, bio. They can't change their ID number.
